### ISSUE TITLE
Search Refactor

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/spark#1745]
The goal is to provide additional drop downs for "simple" search functionality in the context of the different Requests and Tasks screens.

## Tasks

- [x] PRD 1: Need drop downs for general fields
  - [x] Process name
  - [x] Status
  - [x] Requester (user only)
  - [x] Participants (users and groups)

- [x] PRD 2: Need a button to begin search

- [x] PRD 3: When the system is fetching results, the table should show that data is loading (show message and spinner in table)

- [x] PRD 4: Need ability to have advanced search
  - [x] Display a pre-populated long input
  - [x] PRD 5: Ability to toggle between basic and advanced search
  - [x] PRD 6: When toggling to advanced, any basic filters are converted to PMQL and show in the advanced search
  - [x] PRD 7: When toggling to basic, it does not set any of the drop downs

- [x] PRD 9: When using advanced search, if there's a syntax error, a general syntax alert should be shown

- [x] PRD 10: When using these searches for our "Requests By Me" or "In Progress" or "Completed", the fields should automatically be selected to fit that search.
  - [x] Requests by me: Requester = user_id
  - [x] In Progress: Status = ACTIVE
  - [x] Completed: Status = COMPLETED

- [x] New non-api endpoint for population filter drop downs

## Notes
- PRD 8: The URL for the browser does NOT change when using basic/advanced search
